/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppNavigationBar: typeof import('./src/components/AppNavigationBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeCategoriesOptions: typeof import('./src/components/HomeCategoriesOptions.vue')['default']
    HomeEnviarPara: typeof import('./src/components/HomeEnviarPara.vue')['default']
    HomePesquisarNaAmazon: typeof import('./src/components/HomePesquisarNaAmazon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
